import { useEffect, useState } from "react";
import jsPDF from "jspdf";

export default function Reports() {

  const [report, setReport] =
    useState("");

  const [resumeScore, setResumeScore] =
    useState("0");

  const [technicalScore, setTechnicalScore] =
    useState("0");

  const [recommendation, setRecommendation] =
    useState("PENDING");

  const [interviewCount, setInterviewCount] =
    useState(0);

  useEffect(() => {

    const savedReport =
      localStorage.getItem(
        "evaluationReport"
      );

    if (savedReport) {
      setReport(savedReport);
    }

    setResumeScore(
      localStorage.getItem(
        "resumeScore"
      ) || "0"
    );

    setTechnicalScore(
      localStorage.getItem(
        "technicalScore"
      ) || "0"
    );

    setRecommendation(

      localStorage.getItem(
        "resumeDecision"
      ) ||

      localStorage.getItem(
        "recommendation"
      ) ||

      "PENDING"

    );

    setInterviewCount(

      JSON.parse(

        localStorage.getItem(
          "interviewQuestions"
        ) || "[]"

      ).length

    );

  }, []);

  const downloadPDF = () => {

    const reportText =
      localStorage.getItem(
        "evaluationReport"
      ) || "No report available";

    const pdf = new jsPDF();

    pdf.setFontSize(20);

    pdf.text(
      "AI Recruitment Agent",
      10,
      20
    );

    pdf.setFontSize(16);

    pdf.text(
      "Candidate Assessment Report",
      10,
      35
    );

    pdf.setFontSize(11);

    const lines =
      pdf.splitTextToSize(
        reportText,
        180
      );

    pdf.text(
      lines,
      10,
      50
    );

    pdf.save(
      "Candidate_Report.pdf"
    );

  };

  return (

    <div className="p-8 text-white">

      {/* Header */}

      <div className="flex justify-between items-center mb-10">

        <div>

          <h1 className="text-5xl font-bold">
            Recruiter Report Center
          </h1>

          <p className="text-slate-400 mt-3">
            AI Generated Candidate Assessment
            and Hiring Recommendation
          </p>

        </div>

        <button
          onClick={downloadPDF}
          className="
            bg-green-500
            hover:bg-green-600
            px-6
            py-3
            rounded-xl
            font-semibold
            transition
          "
        >
          Download PDF
        </button>

      </div>

      {/* Cards */}

      <div className="grid grid-cols-4 gap-6 mb-10">

        <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6">

          <h3 className="text-slate-400">
            Resume Score
          </h3>

          <p className="text-4xl font-bold mt-2 text-green-400">
            {resumeScore}%
          </p>

        </div>

        <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6">

          <h3 className="text-slate-400">
            Questions Asked
          </h3>

          <p className="text-4xl font-bold mt-2 text-cyan-400">
            {interviewCount}
          </p>

        </div>

        <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6">

          <h3 className="text-slate-400">
            Technical Score
          </h3>

          <p className="text-4xl font-bold mt-2 text-yellow-400">
            {technicalScore}
          </p>

        </div>

        <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6">

          <h3 className="text-slate-400">
            Hiring Decision
          </h3>

          <p
            className={`text-3xl font-bold mt-2 ${
              recommendation === "SHORTLISTED"
                ? "text-green-400"
                : recommendation === "CONSIDER"
                ? "text-yellow-400"
                : "text-red-400"
            }`}
          >
            {recommendation}
          </p>

        </div>

      </div>

      {/* Report */}

      <div
        className="
          bg-slate-900
          border
          border-slate-800
          rounded-3xl
          p-8
        "
      >

        <div className="mb-8">

          <h2 className="text-3xl font-bold">
            Candidate Assessment Report
          </h2>

          <p className="text-slate-400">
            Generated by AI Recruitment Agent
          </p>

        </div>

        <div
          className="
            bg-slate-950
            rounded-2xl
            p-6
          "
        >

          <pre
            className="
              whitespace-pre-wrap
              text-slate-300
              leading-8
              text-base
            "
          >
            {report}
          </pre>

        </div>

      </div>

    </div>

  );

}